version: '3'

networks:
  grid:
services:
# configuration of the hub
  hub:
    image: {Add selenium hub image from dockerhub}/selenium-hub
    ports:
      - "$selenium_host_port:4444"
    networks:
      - grid
    
    deploy:
      
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
        - GRID_BROWSER_TIMEOUT=30000
        - GRID_TIMEOUT=30000
        - GRID_MAX_SESSION=50
        - GRID_MAX_INSTANCES=10
        - GRID_CLEAN_UP_CYCLE=30000    
        - GRID_NEW_SESSION_WAIT_TIMEOUT=30000
# configuration of the grid nodes
  chrome-node:
    image: {Add selenium hub image from dockerhub}/selenium-node-chrome-debug
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port $node_port" /opt/bin/entry_point.sh'
    ports:
      - "$node_port:5555"
    deploy:
      replicas: 5
      restart_policy: 
        condition: on-failure
    networks:
      - grid
    extra_hosts:
      - {adding extra hosts into /etc/hosts} i.e (hostname:ipaddress)
